version: '3.8'

services:
  futurehouse-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FUTUREHOUSE_API_KEY=${FUTUREHOUSE_API_KEY}
      - PORT=5000
      - DEBUG=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s